### ISSUE TITLE
minify javascrip files

### ISSUE THREAD

**Issue by dzizes** [dzizes/kujon.io#115]

**Comment by smola222** [comment]
w wersji pycharm community nie  ma filewatcherow ktore to moga robic z automatu.

można zainstalowac uglifyjs i uruchomic:

./uglifyjs main.js -o main2.js  -p 5 -c -mls -la

i wszystko minimalnizuje.

**Comment by dzizes** [comment]
Trzeba otworzyć o napisać procedurę  i skrypt aby automatyzować instalacje
