### ISSUE TITLE
crawler update for TT only 

### ISSUE THREAD

**Issue by smola222** [dzizes/kujon.io#116]
when in /api/tt current week is fetched from usos - should call crawler to receive next week 
in TODO in /api/tt line 97 insert crawler update for next week.

# insert a call for crawl here for next_monday variable for TT only

**Comment by dzizes** [comment]
powiedz, którą funkcję crawlera mam uruchomić i z jakimi parametrami

**Comment by smola222** [comment]
jak odświeżasz raz dziennie - to lecisz po wszystkich użytkownikach i jeżeli jest poniedziałek to każdemu wywołujesz pobranie harmonogramu na ten tydzień z datą poniedziałkową.  czyli wywołujesz:

     today = date.today()
            monday = today - timedelta(days=(today.weekday()) % 7)
            self.__build_tt(client, user_id, crawl_time, usos, monday)

oczywiście można usunąć też pobrane harmonogramy wcześniej na pobierany tydzień, bo mogło coś się zmienić.
