### ISSUE TITLE
authentication - Upss! Użytkownik już zarejestrowany w UW.

### ISSUE THREAD

**Issue by smola222** [dzizes/kujon.io#141]
jak user wybierze jednego usosa a potem się cofnie i chce wybrać innego - wyświetla się Upss! Użytkownik już zarejestrowany w UW i nic się z tym nie da zrobić.

**Comment by dzizes** [comment]
Nie ma możliwość powrotu tak jak nie ma możliwości rejestracji na 2 usosach

**Comment by smola222** [comment]
nie kumam

Wojciech Smołkowski
wojciech.smolkowski@gmail.com

**Comment by dzizes** [comment]
aplikacja nie przewiduje scieżki cofnięcia się w procesie rejstracji. jest
to błąd.

---
Explicit is better than implicit.

**Comment by smola222** [comment]
zadzwon 

Wojciech Smołkowski
wojciech.smolkowski@gmail.com
