### ISSUE TITLE
what should be in web user settings

### ISSUE THREAD

**Issue by dzizes** [dzizes/kujon.io#19]

**Comment by smola222** [comment]
w ustawieniach są informacje o koncie których nie mozna zmieniać, czyli email, oraz te które można zmieniać tj. imię i nazwisko (uzupełniane z FB lub Googla) oraz hasło, które można sobie ustawić i wtedy można je zmianić. tak jak ci wysyłałem - trzymamy u siebie imie, nazwisko, email, haslo - logowanie przez FB/G jest po emailu.

**Comment by dzizes** [comment]
Jakie hasło?
Ustalilismy że tylko g+ i fb

pon., 8 lut 2016, 00:25 smola222 użytkownik <notifications@github.com>
napisał:
