### ISSUE TITLE
cleanup for unpaired registration

### ISSUE THREAD

**Issue by smola222** [dzizes/kujon.io#85]
when user start to pair account with usos and cancel it at start again with another:

{"USOS_PAIRED": false, "alert_message": "user: already register for usos", "usoses": [{"name": "The University of Wachock - DEMO", "url": "https://usosapps.demo.usos.edu.pl/", "consumer_secret": "4TQESZkkBMFCT2JgtnzAtD5XG6ACZjsEb5vTrDGM", "contact": "dsksysadm@adm.uw.edu.pl", "usos_id": "DEMO", "_id": {"$oid": "56c832ec3d7821e50f078cda"}, "consumer_key": "b9MHLmXygtGDbcL5BCj3"}, {"name": "Uniwersyst Warszawski", "url": "https://usosapps.uw.edu.pl/", "consumer_secret": "Bm7wwuKSekhZKFs77GmP4vxHKgf4B7nFmSzUfWeG", "contact": "dsksysadm@adm.uw.edu.pl", "usos_id": "UW", "_id": {"$oid": "56c832ec3d7821e50f078cdb"}, "consumer_key": "KBt6uWPWUekUzFtNTyY9"}, {"name": "Politechnika Swietokrzystka", "url": "https://api.usos.tu.kielce.pl/", "consumer_secret": "PNMLtvWr6p34tmYSjmDKfNwQEmUdkMwExearQhWA", "contact": "d.walczyk@tu.kielce.pl", "usos_id": "PS", "_id": {"$oid": "56c832ec3d7821e50f078cdc"}, "consumer_key": "equujDB5ZLzTmPfcy2c2"}], "PROJECT_TITLE": "Stara.io", "DEPLOY_URL": "http://localhost:8888"}

**Comment by dzizes** [comment]
new post with ajax call, post error process with ajax error:

https://github.com/dzizes/kujon.io/commit/8d8b6c7f334281b2dc524ad94b3a03efeab7ff03

**Comment by smola222** [comment]
nie wyświetla się nigdzie komunikat o tym że jest sparowany a powinien przekierowywać do strony #main, czyli tej po zalogowaniu.

**Comment by dzizes** [comment]
Nie wiem o co chodzi i jak ostwor
